package com.mykameal.planner.messageclass

object ErrorMessage {


     const val networkError:String="Please check your internet connection"
     const val apiError:String="Something went wrong"
     const val amountNoError:String="Your wallet is empty."
     const val amounthightError:String="Please enter it under Available Balance."
     const val amountlowError:String="Please enter valid Balance."
     const val amountError:String="Invalid amount entered."
     const val mealTypeError:String="Select Meal type."
     const val weekNameError:String="Select Week Name."
     const val selectCookBookError:String="Please Select Cook Book."
     const val ratingError:String="Message can't be empty."
     const val cookBookSelectError:String="Select Cook Book"
     const val amountEmptyError:String="Amount can't be empty."
     const val code: Int=206

     const val apiKey:String="AIzaSyC9NuN_f-wESHh3kihTvpbvdrmKlTQurxw"
     const val emailPhone:String="Please Enter Email/Phone"
     const val recipeName:String="Please Enter Recipe Name"
     const val postCode:String="Please Enter Post Code"
     const val selectGender:String="Please select gender"
     const val pasteUrl:String="Please Paste Url"
     const val registeredEmailPhone:String="Please Enter Registered Email/Phone"
     const val emailAddress="Please Enter your Address"
     const val phoneNumber="Please Enter Phone Number"
     const val cookbookName="Please Enter CookBook Name"
     const val selectPrivatePublic="Please Select Private or Public"
     const val bioError="Bio can't be empty."
     const val cookedMealsError="Please select at least one."
     const val typeError="Select Height Type."
     const val activityTypeError="Select Your Activity Level."
     const val heightError="Height can't be empty."
     const val cardholderError="Card Holder Name can't be empty."
     const val accountNumberError="Account number can't be empty."
     const val cAccountNumberError="Confirm account number can't be empty."
     const val routingNumberError="Routing number can't be empty."
     const val proofofbanError="Please upload proof of bank account."
     const val frontimageError="Please upload front image."
     const val backimageError="Please upload back image."
     const val cardNumberError="Card Number can't be empty."
     const val cvvError="CVV can't be empty."
     const val cvvValidError="Please Enter Valid CVV."
     const val monthError="Please Select Month."
     const val yearError="Please Select Year."
     const val bankVerifyError="Your account is pending. Please contact the administrator or select another account."
     const val name:String="Please Enter Full Name"
     const val emailRegulerExpression="[a-zA-Z0-9._-]+@[a-z]+\\.+[a-z]"


     val networkDialogue: String ="DIALOG_NETWORK"
     const val firstNameError: String ="First name can't be empty."
     const val lastNameError: String ="Last name can't be empty."
     const val emailPhoneError="Email/phone can't be empty."
     const val emailError="Email can't be empty."
     const val phoneError="phone can't be empty."
     const val validEmailPhone:String="Please Enter Valid Email or Phone Number"
     const val validTotalTime:String="Please add total time in minutes"
     const val selectReasonEmpty:String="Please select reason"
     const val dobError:String="Please select DOB"
     const val selectIdTypeError:String="Select id type"
     const val pINError:String="Personal identification number can't be empty."
     const val SNNError:String="SSN can't be empty."
     const val SNNValidError:String="Enter Valid SSN."
     const val addressError:String="Address can't be empty."
     const val countryError:String="Select country."
     const val stateError:String="Select State."
     const val cityError:String="Select City."
     const val postalCodeError:String="Postal code can't be empty."
     const val bankNameError:String="Bank Name can't be empty."
     const val validEmail:String="Please Enter Valid Email Address"
     const val validPhoneNumber:String="Please Enter Valid Phone Number"
     const val password:String="Please Enter Password"
     const val confirmPassword:String="Please Enter\n confirm Password"
     const val passwordMatch:String="Password must be a minimum of 6 characters with an at least 1 number, 1 uppercase & special character."
     const val passwordSame:String="Password and confirm password should be same"
     const val otp:String="Please Enter Otp"
     const val correctOtp:String="Please Enter Correct Otp"
     const val emptyOtp="OTP can't be empty."
     const val address:String="Please Enter your Address."
     const val profileUpload:String="Please upload your picture"
     const val manufactureUpload:String="Please add manufacture name"
     const val subject:String="Please select subject"
     const val descriptions:String="Please enter description"
     const val areaError:String="Area can't be empty."
     const val phoneVerifyError="Please verify phone number first."
     const val emailVerifyError="Please verify email first."
     const val itemSelectError:String="Please select at least one item."
     const val configurationError:String="Configuration can't be empty."
     const val systemtypeError:String="System type can't be empty."
     const val refrigerationtypeError:String="Refrigeration type can't be empty."
     const val thermostatError:String="Thermostat Location can't be empty."
     const val filterError:String="Filter can't be empty."
     const val manufacturerError:String="Please Select Manufacturer."
     const val componentError:String="Component can't be empty."
     const val modelError:String="Model can't be empty."
     const val serialError:String="Serial can't be empty."
     const val imageError:String="Image can't be empty."
     const val catError:String="Please Select Category."
     const val subCatError:String="Please Select Sub-Category."
     const val milesError:String="Please Select Miles."
     const val serviceLocationError:String="Service Location Can't be empty."
     const val settingImageError="Please go to setting Enable Permission"
     const val addressUpload:String="Please upload Address Proof."
     const val idProofUpload:String="Please upload Id Proof."
     const val selfieProofUpload:String="Please upload Selfie Proof."
     const val cookbookUpload:String="Please upload cookbook image."

     const val locationError="Please Turn On Your Location.Your location helps us enhance your overall experience, making it more convenient and efficient. Rest assured, your privacy is our priority, and your location data will be handled securely and responsibly.Thank you for helping us serve you better!"
     const val verifyStatus="Verified"
     const val verifyNowStatus="Verify now"
     const val emailVaildStatus="invalid email"
     const val phoneVaildStatus="invalid phone"
     const val emailValidationError="Please enter valid email."
     const val checkListError="Please Select At Least One."
     const val checkError="Please Select At Least One."






}